#ifndef NM_EFFECT_SCRATCHES_INCLUDED
#define NM_EFFECT_SCRATCHES_INCLUDED

// =============================================================================
// Scratches.hlsl — filter/scratches (func: "scratches")
//
// Ported PIXEL-IDENTICALLY from the canonical WGSL source:
//   shaders/effects/filter/scratches/wgsl/scratchesBlend.wgsl
//
// Film-scratch overlay: the overlayTex is a CPU-baked white-line scratch mask
// (generated by traceWorms in asyncInit). This pass max-blends those scratches
// over the input image. Only the overlay's alpha channel drives strength.
//
// WGSL main():
//   let coord = vec2<i32>(i32(pos.x), i32(pos.y));   // integer pixel coord
//   let base    = textureLoad(inputTex,  coord, 0);
//   let overlay = textureLoad(overlayTex, coord, 0);
//   let scratchStrength = overlay.a * alpha;
//   let result = max(base.rgb, vec3<f32>(scratchStrength));
//   return vec4<f32>(result, base.a);
//
// PORTING-GUIDE notes / hazards handled:
//  * Both textures are loaded with textureLoad (integer coords, no sampler).
//    HLSL equivalent: Texture2D.Load(int3(coord, 0)). No UV division needed.
//  * coord = int2(pos.x, pos.y) — truncation, not rounding. NM_FragCoord returns
//    px+0.5 floats; cast to int2 truncates the 0.5 → exact pixel index. Matches
//    the WGSL int(pos.x) truncation.
//  * No per-effect UV coordinate hazard: this pass never normalises coords.
//  * No PRNG / no PCG / no float-bit hazards in this effect.
//  * Linear, clamp-to-edge, non-sRGB sampler is unused here (textureLoad), but
//    the Texture2D declarations are present for runtime binding.
//  * The overlayTex is CPU-generated (asyncInit/traceWorms). The C# runtime must
//    supply it as an external RenderTexture (RGBA8 or ARGBHalf) on every frame
//    where the overlay has changed.
//
// Input textures (two):
//   inputTex   — the main scene/effect input (reference binding 1)
//   overlayTex — the CPU-baked scratch mask   (reference binding 2)
//
// Per-effect uniforms:
//   float alpha  — scratch intensity [0,1], default 0.75
//   (density and seed are CPU-side only — they control traceWorms, not the GPU pass)
// =============================================================================

#include "../../Include/NMFullscreen.hlsl"

// ---- Input textures (textureLoad — no sampler required for the blend pass) ---
Texture2D inputTex;
Texture2D overlayTex;

// ---- Per-effect named uniform (definition.js globals.alpha.uniform) ----------
float alpha;   // [0,1] default 0.75

// =============================================================================
// nm_scratches_blend — core per-pixel evaluation.
//   base    : RGBA loaded from inputTex  at integer pixel coord
//   overlay : RGBA loaded from overlayTex at integer pixel coord
// Returns RGBA output matching the WGSL main() body exactly.
// =============================================================================
float4 nm_scratches_blend(float4 base, float4 overlay)
{
    // WGSL: let scratchStrength = overlay.a * alpha;
    float scratchStrength = overlay.a * alpha;

    // WGSL: let result = max(base.rgb, vec3<f32>(scratchStrength));
    float3 result = max(base.rgb, float3(scratchStrength, scratchStrength, scratchStrength));

    // WGSL: return vec4<f32>(result, base.a);
    return float4(result, base.a);
}

// ---- Pass: "blend" (progName "scratchesBlend") -------------------------------
float4 NMFrag_scratchesBlend(NMVaryings i) : SV_Target
{
    // WGSL: let coord = vec2<i32>(i32(pos.x), i32(pos.y));
    // NM_FragCoord returns px+0.5 (top-left, pixel-centered). Truncating to int2
    // strips the 0.5, giving the pixel index — identical to WGSL i32(pos.x).
    int2 coord = int2(NM_FragCoord(i));

    // WGSL: textureLoad(inputTex, coord, 0) / textureLoad(overlayTex, coord, 0)
    float4 base    = inputTex.Load(int3(coord, 0));
    float4 overlay = overlayTex.Load(int3(coord, 0));

    return nm_scratches_blend(base, overlay);
}

#endif // NM_EFFECT_SCRATCHES_INCLUDED
